---
dependency:
  name: galaxy

driver:
  name: podman

provisioner:
  name: ansible

platforms:
  - name: fedora-42
    image: fedora:42
    pre_build_image: true

  - name: debian-12
    image: debian:12
    pre_build_image: true

