---
dependency:
  name: galaxy
  enabled: false

driver:
  name: podman

provisioner:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

platforms:
  - name: fedora-${FEDORA_VERSION:-44}
    image: fedora:${FEDORA_VERSION:-44}
    pre_build_image: true

  - name: debian-${DEBIAN_VERSION:-13}
    image: debian:${DEBIAN_VERSION:-13}
    pre_build_image: true
