---
- name: Ensure Python is installed
  hosts: all
  gather_facts: false
  roles:
    - install_python

- name: Set up Ansible dependencies
  hosts: all
  tasks:
    - name: Install Debian-based dependencies
      when: ansible_os_family == 'Debian'
      block:
        - name: Check if python3-apt is installed
          ansible.builtin.command:
            cmd: dpkg-query --show --showformat='${Status}' python3-apt
          register: python3_apt_installed
          ignore_errors: true

        - name: Install python3-apt
          ansible.builtin.command:
            cmd: apt install -y python3-apt
          become: true
          when: python3_apt_installed.rc != 0

        - name: Install gpg
          ansible.builtin.apt:
            name: gnupg

    - name: Install Darwin-based dependencies
      ansible.builtin.include_role:
        name: install_homebrew
      when: ansible_os_family == 'Darwin'
