---
# Fedora 42
- name: Ensure official COPR for Wezterm is enabled
  community.general.copr:
    name: wezfurlong/wezterm-nightly
  notify: refresh dnf cache

- name: Flush queued handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Wezterm is installed
  ansible.builtin.dnf:
    name: wezterm

