---
# Fedora 42
- name: Enable official COPR for Wezterm
  community.general.copr:
    name: wezfurlong/wezterm-nightly
  notify: refresh dnf cache

- name: Flush queued handlers
  ansible.builtin.meta: flush_handlers

- name: Install Wezterm
  ansible.builtin.dnf:
    name: wezterm

