---
- name: Check if sudo is installed
  ansible.builtin.raw: command -v sudo
  register: sudo_installed
  ignore_errors: true
  changed_when: false

- name: Check if the system is Debian-based
  ansible.builtin.raw: ls /etc/debian_version
  register: is_debian
  ignore_errors: true
  changed_when: false

- name: Install sudo for Debian-based systems
  ansible.builtin.raw: apt-get install -y sudo
  when:
    - sudo_installed.rc != 0
    - is_debian.rc == 0
  changed_when: true
