---
- name: Check if homebrew is installed
  ansible.builtin.raw: command -v brew
  register: homebrew_installed
  ignore_errors: true
  changed_when: false

- name: Install homebrew
  ansible.builtin.raw: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_installed.rc != 0
  changed_when: true
